name: Keep Streamlit App Alive

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          curl -sS https://h2lzomy25z7wad5moa7tjy.streamlit.app/ > /dev/null
